### ISSUE TITLE
代码围栏不识别

### ISSUE THREAD

**Issue by m0ch3** [bytemate/chatapi-single#12]
# chatgpt回答中存在代码围栏时，无法获取到围栏内容。

## chatapi
```
curl -X "POST" "https://xxxx/message/holego1ts" -H 'Content-Type: application/json; charset=utf-8' -d $'{"message": "写一个聊天机器人前端代码"}'
{"response":"这是一个基于 JavaScript 和 HTML 的简单聊天机器人前端代码示例：这是一个非常基础的示例，可以作为更复杂的聊天机器人应用程序的起点。你可以通过向服务器请求数据并使用 API 获取更多信息来改进它，例如通过使用自然语言处理或机器学习算法等。\n"}
```

## 官方网页展示
![20230214094828](https://user-images.githubusercontent.com/62938392/218617581-c88ca71b-cd7e-41b6-ab32-8edc738ae31f.jpg)

**Comment by rilweic** [comment]
+10086

**Comment by rilweic** [comment]
我看chatgpt上的接口Response Header里面的content-type为：text/event-stream。
![image](https://user-images.githubusercontent.com/9164714/218979940-c5d24b71-a0e7-408d-9c42-e0aa28e1ee74.png)
不知道是不是客户端请求因为这个原因所以不显示代码的内容

**Comment by m0ch3** [comment]
查看chatgpt的回答数据发现，代码围栏使用的是markdown格式，于是尝试设置`.env`: `MARKDOWN=true`，解决了这个问题

**Comment by m0ch3** [comment]
建议修改readme增加相关说明，或修改`.env`以及`lib.ts`中的默认配置

**Comment by drttcrh** [comment]
> 建议修改readme增加相关说明，或修改`.env`以及`lib.ts`中的默认配置

env还有两个参数，我觉得应该也标注一下，
- HOST: 主机地址
- PORT: 服务端口
