### ISSUE TITLE
Docker拉取镜像报错

### ISSUE THREAD

**Issue by emengweb** [bytemate/chatapi-single#23]
使用docker-compose.yml文件构建容器，pull镜像时报错：
```
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /app/node_modules/tmp/LICENSE: invalid argument
```

**Comment by emengweb** [comment]
手动build本地镜像可以正常启动

**Comment by sbbbsbbb** [comment]
奇怪,我手动build 报错
------
 > [8/8] RUN npm run build:
#13 1.648 
#13 1.648 > chatgpt-api-single@1.0.0 build
#13 1.648 > tsc
#13 1.648 
#13 4.009 src/index.ts(259,14): error TS2769: No overload matches this call.
#13 4.009   Overload 1 of 6, '(port: number, hostname: string, backlog: number, callback?: (() => void) | undefined): Server<typeof IncomingMessage, typeof ServerResponse>', gave the following error.
#13 4.009     Argument of type 'string | 4000' is not assignable to parameter of type 'number'.
#13 4.009       Type 'string' is not assignable to type 'number'.
#13 4.009   Overload 2 of 6, '(port: number, hostname: string, callback?: (() => void) | undefined): Server<typeof IncomingMessage, typeof ServerResponse>', gave the following error.
#13 4.009     Argument of type 'string | 4000' is not assignable to parameter of type 'number'.
#13 4.009       Type 'string' is not assignable to type 'number'.
------

**Comment by myfingerhurt** [comment]
https://github.com/bytemate/chatapi-single/pull/21
