### ISSUE TITLE
请问是不是无法正常工作了?

### ISSUE THREAD

**Issue by sbbbsbbb** [bytemate/chatapi-single#27]
搭建完docker logs 显示成功
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
🎉 Started chatgpt success!
🚀 Server ready at: http://localhost:4000/
但是 curl 显示
curl: (52) Empty reply from server

**Comment by LouisTay** [comment]
@yanshibin 请参考 https://github.com/bytemate/chatapi-single/issues/26

**Comment by LouisTay** [comment]
具体原因参见：https://www.cnblogs.com/selwynli/p/16183737.html

**Comment by sbbbsbbb** [comment]
> @yanshibin 请参考 #26

--net=host 使用docker的时候 添加host 参数也可以
