### ISSUE TITLE
app.listen 默认监听host设定为localhost之后，可能导致docker映射端口无法访问

### ISSUE THREAD

**Issue by SimonTheCoder** [bytemate/chatapi-single#32]
之前版本app.listen只设定了监听端口，默认情况下，会监听全部interface。
当前版本添加了HOST环境变量提供自定义监听地址的同时，也指定了localhost为默认监听地址。
在Docker中运行的情况下，如果没有将HOST环境变量设定为：0.0.0.0的话，将无法从container外访问服务。

建议在readme中以及.env文件示例中添加HOST=0.0.0.0的默认设定。

**Comment by fuergaosi233** [comment]
You're right

**Comment by fuergaosi233** [comment]
https://github.com/bytemate/chatapi-single/pull/33
