### ISSUE TITLE
It is not possible to start through Docker in the Quickstart.

### ISSUE THREAD

**Issue by vinsec** [bytemate/chatapi-single#7]
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "data.db" at "file:../data/data.db"

SQLite database data.db created at file:../data/data.db

1 migration found in prisma/migrations

Applying migration `20230211124232_init`

The following migration have been applied:

migrations/
  └─ 20230211124232_init/
    └─ migration.sql

All migrations have been successfully applied.
Starting chatgpt with config: {
  "email": "cxxxxxxxx5@hotmail.com",
  "password": "xxxxxx1",
  "isProAccount": false,
  "markdown": false,
  "debug": false,
  "isGoogleLogin": false,
  "isMicrosoftLogin": false,
  "minimize": false
}
no access token
Starting chatgpt failed, retrying...
ChatGPTError: Failed to authenticate session
    at ChatGPTAPIBrowser.initSession (file:///app/node_modules/chatgpt/build/index.js:1448:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retries (/app/dist/index.js:150:9)
    at async main (/app/dist/index.js:149:5)

**Comment by ShenQingchuan** [comment]
Same issue here.

**Comment by Lorca-R** [comment]
Maybe you should check the location where the code is running at.
Some regions (HK etc) are not permitted to use ChatGPT

**Comment by fuergaosi233** [comment]
Make sure ChatGPT is available in your region
