### ISSUE TITLE
与以上问题同样出现

### ISSUE THREAD

**Issue by emmmnaadada** [bytemate/chatapi-single#9]
无法使用谷歌登录

已关闭2次验证

**Comment by myfingerhurt** [comment]
[Try Sign in with App Passwords ](https://support.google.com/accounts/answer/185833?hl=en)

**Comment by emmmnaadada** [comment]
> [Try Sign in with App Passwords ](https://support.google.com/accounts/answer/185833?hl=en)

无法使用

**Comment by fuergaosi233** [comment]
抱歉这个我暂时也没办法提供更多帮助， 我没有Google 账户， 也没有精力去维护原作者的 Google 登录逻辑。
